version: '3'
services:
    ntp:
        container_name: ntp
        hostname: ntp
        build: .
        ##ports:
        ##  - "123/udp"
        network_mode: host
        
        #restart: unless-stopped
        
        restart: "no"
        tty: true
        #command: tail -F /dev/null
        command: >
            bash -c "service ntp start 
            && tail -F /dev/null"