version: '3.2'
services:
    ntp:
        container_name: ntp
        hostname: ntp
        build: .
        ports:
          - target: 123
            published: 123
            protocol: udp
            mode: host
        restart: unless-stopped
        tty: true
        command: >
            bash -c "service ntp start 
            && tail -F /dev/null"