version: '3'
services:
    ntp:
        container_name: ntp
        hostname: ntp
        build: .
        ports:
          - "123/udp"
        #restart: unless-stopped
        #commend: /usr/sbin/ntpd
        
        restart: "no"
        tty: true
        command: tail -F anything
